
service: armada # NOTE: update this with your service name
#app: your-app-name
#tenant: your-tenant-name

custom:
  version: v1
  users:
    handler: src/handlers/usersHandler
    path: ${self:custom.version}/users
  martialArts:
    handler: src/handlers/martialArtsHandler
    path: ${self:custom.version}/martialArts
  academies:
    handler: src/handlers/academiesHandler
    path: ${self:custom.version}/academies
  locations:
    handler: src/handlers/locationsHandler
    path: ${self:custom.version}/locations
  scheduleItems:
    handler: src/handlers/scheduleItemsHandler
    path: ${self:custom.version}/scheduleItems
  classes:
    handler: src/handlers/classesHandler
    path: ${self:custom.version}/classes
  cors:
    origins:
      - 'http://localhost*'
    headers:
      - Content-Type
      - X-Amz-Date
      - Authorization
      - X-Api-Key
      - X-Amz-Security-Token
      - X-Amz-User-Agent
      - X-Amz-User-Agent
      - Access-Control-Allow-Origin
      - X-Xsrf-Token
      - Api-Key
      - Cookie
    allowCredentials: true

provider:
  name: aws
  runtime: nodejs10.x
  environment: ${file(./serverless.env.yml):${opt:stage, 'dev'}}
  role: arn:aws:iam::302314551855:role/Armada

functions:
  uploadUserImage:
    handler: ${self:custom.users.handler}.uploadImage
    events:
      - http:
          path: ${self:custom.users.path}/{id}/{type}
          method: post
  register:
    handler: ${self:custom.users.handler}.register
    events:
      - http:
          path: ${self:custom.users.path}/register
          method: post
  forgotPassword:
    handler: ${self:custom.users.handler}.forgotPassword
    events:
      - http:
          path: ${self:custom.users.path}/forgotPassword
          method: post
  updatePassword:
    handler: ${self:custom.users.handler}.updatePassword
    events:
      - http:
          path: ${self:custom.users.path}/updatePassword/{id}
          method: patch
  login:
    handler: ${self:custom.users.handler}.login
    events:
      - http:
          path: ${self:custom.users.path}/login
          method: post
  logout:
    handler: ${self:custom.users.handler}.logout
    events:
      - http:
          path: ${self:custom.users.path}/logout
          method: get
  createUser:
    handler: ${self:custom.users.handler}.create
    events:
      - http:
          path: ${self:custom.users.path}
          method: post
  updateUser:
    handler: ${self:custom.users.handler}.update
    events:
      - http:
          path: ${self:custom.users.path}/{id}
          method: put
          request:
            parameters:
              paths:
                id: true
  getUser:
    handler: ${self:custom.users.handler}.get
    events:
      - http:
          path: ${self:custom.users.path}/{id}
          method: get
          request:
            parameters:
              paths:
                id: true
  listUsers:
    handler: ${self:custom.users.handler}.list
    events:
      - http:
          path: ${self:custom.users.path}
          method: get
  deleteUser:
    handler: ${self:custom.users.handler}.delete
    events:
      - http:
          path: ${self:custom.users.path}/{id}
          method: delete
          request:
            parameters:
              paths:
                id: true
  createMartialArts:
    handler: ${self:custom.martialArts.handler}.create
    events:
      - http:
          path: ${self:custom.martialArts.path}
          method: post
  updateMartialArts:
    handler: ${self:custom.martialArts.handler}.update
    events:
      - http:
          path: ${self:custom.martialArts.path}/{id}
          method: put
          request:
            parameters:
              paths:
                id: true
  getMartialArts:
    handler: ${self:custom.martialArts.handler}.get
    events:
      - http:
          path: ${self:custom.martialArts.path}/{id}
          method: get
          request:
            parameters:
              paths:
                id: true
  listMartialArts:
    handler: ${self:custom.martialArts.handler}.list
    events:
      - http:
          path: ${self:custom.martialArts.path}
          method: get
  deleteMartialArts:
    handler: ${self:custom.martialArts.handler}.delete
    events:
      - http:
          path: ${self:custom.martialArts.path}/{id}
          method: delete
          request:
            parameters:
              paths:
                id: true
  createSchools:
    handler: handlers/schoolsHandler.create
    events:
      - http:
          path: schools
          method: post
  updateSchools:
    handler: handlers/schoolsHandler.update
    events:
      - http:
          path: schools/{id}
          method: put
          request:
            parameters:
              paths:
                id: true
  getSchools:
    handler: handlers/schoolsHandler.get
    events:
      - http:
          path: schools/{id}
          method: get
          request:
            parameters:
              paths:
                id: true
  listSchools:
    handler: handlers/schoolsHandler.list
    events:
      - http:
          path: schools
          method: get
  deleteSchools:
    handler: handlers/schoolsHandler.delete
    events:
      - http:
          path: schools/{id}
          method: delete
          request:
            parameters:
              paths:
                id: true
  uploadAcademyImage:
    handler: ${self:custom.academies.handler}.uploadImage
    events:
      - http:
          path: ${self:custom.academies.path}/{id}/{type}
          method: post
  createAcademies:
    handler: ${self:custom.academies.handler}.create
    events:
      - http:
          path: ${self:custom.academies.path}
          method: post
  updateAcademies:
    handler: ${self:custom.academies.handler}.update
    events:
      - http:
          path: ${self:custom.academies.path}/{id}
          method: put
          request:
            parameters:
              paths:
                id: true
  getAcademies:
    handler: ${self:custom.academies.handler}.get
    events:
      - http:
          path: ${self:custom.academies.path}/{id}
          method: get
          request:
            parameters:
              paths:
                id: true
  listAcademies:
    handler: ${self:custom.academies.handler}.list
    events:
      - http:
          path: ${self:custom.academies.path}
          method: get
  deleteAcademies:
    handler: ${self:custom.academies.handler}.delete
    events:
      - http:
          path: ${self:custom.academies.path}/{id}
          method: delete
          request:
            parameters:
              paths:
                id: true
  getUserAcademies:
    handler: ${self:custom.academies.handler}.getUserAcademies
    events:
      - http:
          path: ${self:custom.academies.path}/byUser/{id}
          method: get
          request:
            parameters:
              paths:
                id: true
  createLocations:
    handler: ${self:custom.locations.handler}.create
    events:
      - http:
          path: ${self:custom.locations.path}
          method: post
  updateLocations:
    handler: ${self:custom.locations.handler}.update
    events:
      - http:
          path: ${self:custom.locations.path}/{id}
          method: put
          request:
            parameters:
              paths:
                id: true
  getLocations:
    handler: ${self:custom.locations.handler}.get
    events:
      - http:
          path: ${self:custom.locations.path}/{id}
          method: get
          request:
            parameters:
              paths:
                id: true
  listLocations:
    handler: ${self:custom.locations.handler}.list
    events:
      - http:
          path: ${self:custom.locations.path}
          method: get
  deleteLocations:
    handler: ${self:custom.locations.handler}.delete
    events:
      - http:
          path: ${self:custom.locations.path}/{id}
          method: delete
          request:
            parameters:
              paths:
                id: true
  createScheduleItems:
    handler: ${self:custom.scheduleItems.handler}.create
    events:
      - http:
          path: ${self:custom.scheduleItems.path}
          method: post
  updateScheduleItems:
    handler: ${self:custom.scheduleItems.handler}.update
    events:
      - http:
          path: ${self:custom.scheduleItems.path}/{id}
          method: put
          request:
            parameters:
              paths:
                id: true
  getScheduleItems:
    handler: ${self:custom.scheduleItems.handler}.get
    events:
      - http:
          path: ${self:custom.scheduleItems.path}/{id}
          method: get
          request:
            parameters:
              paths:
                id: true
  listScheduleItems:
    handler: ${self:custom.scheduleItems.handler}.list
    events:
      - http:
          path: ${self:custom.scheduleItems.path}
          method: get
  deleteScheduleItems:
    handler: ${self:custom.scheduleItems.handler}.delete
    events:
      - http:
          path: ${self:custom.scheduleItems.path}/{id}
          method: delete
          request:
            parameters:
              paths:
                id: true
  createClasses:
    handler: ${self:custom.classes.handler}.create
    events:
      - http:
          path: ${self:custom.classes.path}
          method: post
  attendClasses:
    handler: ${self:custom.classes.handler}.attend
    events:
      - http:
          path: ${self:custom.classes.path}/attend
          method: patch
  unattendClasses:
    handler: ${self:custom.classes.handler}.unattend
    events:
      - http:
          path: ${self:custom.classes.path}/unattend
          method: patch
  updateClasses:
    handler: ${self:custom.classes.handler}.update
    events:
      - http:
          path: ${self:custom.classes.path}/{id}
          method: put
          request:
            parameters:
              paths:
                id: true
  getClasses:
    handler: ${self:custom.classes.handler}.get
    events:
      - http:
          path: ${self:custom.classes.path}/{id}
          method: get
          request:
            parameters:
              paths:
                id: true
  listClasses:
    handler: ${self:custom.classes.handler}.list
    events:
      - http:
          path: ${self:custom.classes.path}
          method: get
  deleteClasses:
    handler: ${self:custom.classes.handler}.delete
    events:
      - http:
          path: ${self:custom.classes.path}/{id}
          method: delete
          request:
            parameters:
              paths:
                id: true
plugins:
  - serverless-offline
